import spacy
import en_core_web_lg
from spacy.matcher import PhraseMatcher
import pandas as pd
from fuzzywuzzy import fuzz
# import skill extractor
from skillNer.skill_extractor_class import SkillExtractor
from skillNer.general_params import SKILL_DB
import spacy
import database


# init params of skill extractor
nlp = en_core_web_lg.load()
# init skill extractor
skill_extractor = SkillExtractor(nlp, SKILL_DB, PhraseMatcher)

# extract skills from job_description
# loader = TextLoader("Tanisha Patel .txt")
def check_similarity(skill_resume, all_skills, threshold=100):
    # Check similarity using fuzzywuzzy library
    similarities = [fuzz.token_set_ratio(skill_resume, skill_data) for skill_data in all_skills]
    max_similarity = max(similarities)

    if max_similarity >= threshold:
        return True
    else:
        return False


def temp(file_path: str):
    txt_file = open(file_path, 'r', encoding='utf-8')
    job_description = txt_file.read()  


    annotations = skill_extractor.annotate(job_description)

    data = annotations
    # Extracting 'doc_node_value' field into a list
    doc_node_values = [result['doc_node_value'] for result in data['results']['full_matches']]
    doc_node_values += [result['doc_node_value'] for result in data['results']['ngram_scored']]

    # print(doc_node_values)

    doc_node_values = pd.Series(doc_node_values)
    
    # Load the skills from the resume and dataset CSV files
    resume_skills = doc_node_values  # Replace with your actual file path
    all_skills = pd.Series(['programming',
    'python',
    'java',
    'c++',
    'reactjs',
    'web development',
    'html',
    'cs',
    'javascript',
    'reactjs',
    'flask',
    'flutter',
    'database management: sql',
    'mongodb',
    'cloud computing: aws (ec2',
    's3)',
    'project management',
    'communication',
    'problem solving',
    'time management',
    'data analysis: excel',
    'panda',
    'numpy',
    'ux/ui design',
    'network security',
    'statistical modeling',
    'adaptability',
    'collaboration',
    'leadership',
    'emotional intelligence',
    'healthcare informatics',
    'e-commerce strategies',
    'renewable energy technologies',
    'certifications: csm',
    'aws certified solutions architect',
    'pmp',
    'languages: english',
    'spanish',
    'french (basic)',
    'software development',
    'responsive web design',
    'data storage and retrieval',
    'cloud solutions',
    'cross-functional team leadership',
    'critical thinking',
    'ux/ui prototyping',
    'network protection',
    'data interpretation',
    'agile methodologies',
    'digital marketing',
    'customer engagement',
    'environmental impact assessment',
    'continuous language learning',
    'multicultural communication',
    'team collaboration',
    'project delivery',
    'interpersonal skills',
    'electronic health records (ehr)',
    'online sales optimization',
    'sustainable energy',
    'scrum methodology',
    'system design',
    'security measures',
    'decision-making skills',
    'data standards',
    'interoperability',
    'environmental awareness',
    'language proficiency',
    'version control (e.g.',
    'git)',
    'front-end frameworks (e.g.',
    'react',
    'angular)',
    'back-end frameworks (e.g.',
    'django',
    'flask)',
    'api design and integration',
    'mobile app development',
    'devops practices',
    'containerization (e.g.',
    'docker)',
    'continuous integration/continuous deployment (ci/cd)',
    'machine learning concepts',
    'natural language processing (nlp)',
    'cybersecurity measures',
    'blockchain technology',
    'big data technologies (e.g.',
    'hadoop',
    'spark)',
    'virtualization technologies',
    'a/b testing',
    'user research',
    'wireframing',
    'cloud security',
    'risk assessment',
    'marketing analytics',
    'sales forecasting',
    'customer relationship management (crm)',
    'supply chain management',
    'quality assurance and testing',
    'agile project tracking tools (e.g.',
    'jira)',
    'network protocols (e.g.',
    'tcp/ip)',
    'serverless architecture',
    'microservices architecture',
    'api documentation',
    'technical writing',
    'negotiation skills',
    'conflict resolution',
    'decision-making under uncertainty',
    'strategic planning',
    'financial literacy',
    'budget management',
    'presentation skills',
    'public speaking',
    'creative thinking',
    'critical evaluation of information',
    'research and information synthesis',
    'project coordination',
    'team building',
    'employee training and development',
    'time estimation',
    'customer service',
    'sales skills',
    'market research',
    'vendor management',
    'public relations',
    'emotional resilience',
    'stress management',
    'adaptation to change',
    'cross-cultural communication',
    'networking',
    'conflict management',
    'leadership development',
    'decision-making under pressure',
    'problem-solving in ambiguous situations',
    'stakeholder engagement',
    'entrepreneurial mindset',
    'business development',
    'data privacy compliance',
    'regulatory compliance',
    'legal knowledge',
    'contract negotiation',
    'supply chain optimization',
    'change management',
    'employee engagement',
    'diversity and inclusion',
    'crisis management',
    'sustainability practices',
    'corporate social responsibility',
    'media relations',
    'market trend analysis',
    'foreign language proficiency',
    'cultural sensitivity',
    'conflict of interest resolution',
    'client relationship management',
    'ethical decision-making',
    'remote collaboration',
    'time zone management',
    'vendor negotiation',
    'financial analysis',
    'risk management',
    'business process optimization',
    'mentoring and coaching',
    'workplace safety',
    'data governance',
    'influencing skills',
    'public policy analysis',
    'community engagement',
    'advocacy',
    'grant writing',
    'event planning and coordination',
    'volunteer management',
    'fundraising',
    'crisis communication',
    'interpersonal conflict resolution',
    'empathy',
    'cross-functional collaboration',
    'client retention',
    'business analytics',
    'lean six sigma',
    'conflict of interest resolution',
    'social media management',
    'emotional intelligence',
    'time blocking',
    'task delegation',
    'organizational skills',
    'knowledge management',
    'self-motivation',
    'customer feedback analysis',
    'it service management',
    'remote team leadership',
    'knowledge transfer',
    'learning agility',
    'global business awareness',
    'business continuity planning',
    'influencer marketing',
    'cultural competence',
    'design thinking',
    'storytelling',
    'vendor relationship management',
    'brand development',
    'it governance',
    'competitive analysis',
    'ethical leadership',
    'social responsibility planning',
    'remote collaboration tools',
    'designing training programs',
    'information security compliance',
    'workplace wellness programs',
    'customer success management',
    'regulatory reporting',
    'team conflict resolution',
    'presentation design',
    'behavioral economics',
    'continuous learning culture',
    'multitasking',
    'crowdsourcing',
    'sustainability reporting',
    'organizational change',
    'corporate training',
    'influencing without authority',
    'grant management',
    'workplace inclusivity',
    'blockchain governance',
    'user documentation',
    'it risk management',
    'microsoft office suite: word',
    'excel',
    'powerpoint',
    'outlook',
    'google workspace: docs',
    'sheet',
    'slide',
    'gmail',
    'project management tools: trello',
    'asana',
    'version control systems: git',
    'github',
    'customer relationship management (crm) software',
    'collaboration and communication tools: slack',
    'microsoft teams',
    'data visualization tools: tableau',
    'power bi',
    'code editors: visual studio code',
    'sublime text',
    'integrated development environments (ides)',
    'content management systems: wordpress',
    'drupal',
    'graphic design software: adobe creative cloud',
    'video editing tools: adobe premiere',
    'final cut pro',
    'database management systems: mysql',
    'postgresql',
    'cloud platforms: aws',
    'azure',
    'google cloud',
    'customer support software: zendesk',
    'freshdesk',
    'social media management tools: hootsuite',
    'buffer',
    'marketing automation platforms: hubspot',
    'marketo',
    'continuous integration/continuous deployment (ci/cd) tools',
    'virtualization tools: vmware',
    'virtualbox',
    'network monitoring tools: wireshark',
    'nagios',
    'cybersecurity tools: wireshark',
    'metasploit',
    'e-commerce platforms: shopify',
    'magento',
    'learning management systems (lms)',
    'data warehousing tools: snowflake',
    'amazon redshift',
    'password management tools: lastpass',
    '1password',
    'machine learning algorithms',
    'deep learning frameworks: tensorflow',
    'pytorch',
    'natural language processing (nlp)',
    'computer vision',
    'reinforcement learning',
    'neural network design',
    'ai model deployment',
    'transfer learning',
    'data preprocessing for ml',
    'feature engineering',
    'model evaluation and optimization',
    'hyperparameter tuning',
    'explainable ai',
    'time series analysis',
    'anomaly detection',
    'generative adversarial networks (gans)',
    'automl (automated machine learning)',
    'ai ethics and bias mitigation',
    'chatbot development',
    'speech recognition',
    'image classification',
    'predictive modeling',
    'recommendation systems',
    'clustering algorithms',
    'time series forecasting',
    'structural design in civil engineering',
    'project planning and management in civil engineering',
    'geotechnical engineering in civil engineering',
    'environmental impact assessment in civil engineering',
    'cad/cam design in mechanical engineering',
    'thermodynamics in mechanical engineering',
    'finite element analysis (fea) in mechanical engineering',
    'robotics in mechanical engineering',
    'circuit design in electrical engineering',
    'power systems in electrical engineering',
    'control systems in electrical engineering',
    'renewable energy systems in electrical engineering',
    'reactjs',
    'flask',
    'flutter',
    'process optimization in chemical engineering',
    'material science in chemical engineering',
    'aerodynamics in aerospace engineering',
    'avionics in aerospace engineering',
    'medical imaging in biomedical engineering',
    'biomaterials in biomedical engineering',
    'clinical diagnosis for doctors',
    'patient care and communication for doctors',
    'medical research for doctors',
    'patient advocacy in nursing',
    'emergency response in nursing',
    'medication management for pharmacists',
    'regulatory compliance for pharmacists',
    'animal care in veterinary medicine',
    'surgical procedures in veterinary medicine',
    'architectural design',
    'painting and drawing in fine arts',
    'stage management in performing arts',
    'adobe creative suite in graphic design',
    'textile selection in fashion design',
    'space planning in interior design',
    'sustainability practices in environmental science',
    'pollution control in environmental science',
    'financial analysis',
    'risk management',
    'budgeting and forecasting',
    'investment analysis',
    'financial modeling',
    'auditing',
    'tax planning',
    'regulatory compliance',
    'corporate finance',
    'financial reporting',
    'data analysis in finance',
    'business valuation',
    'asset management',
    'portfolio management',
    'financial planning',
    'econometrics',
    'derivatives trading',
    'merger and acquisition analysis',
    'fraud detection',
    'credit analysis',
    'treasury management',
    'cost accounting',
    'international finance',
    'financial software proficiency (e.g.',
    'sap',
    'quickbooks)',
    'securities and exchange compliance',
    'private equity analysis',
    'corporate governance',
    'fixed income analysis',
    'financial risk assessment',
    'cryptocurrency knowledge',
    'legal research and writing (legal profession)',
    'case management (legal profession)',
    'financial analysis (finance)',
    'risk assessment (insurance)',
    'quality control (manufacturing)',
    '3d modeling (animation and design)',
    'video editing (media and entertainment)',
    'emergency medicine (emergency medical services)',
    'clinical psychology (psychology)',
    'social work (social services)',
    'curriculum development (education)',
    'classroom management (education)',
    'event planning (event management)',
    'culinary arts (culinary)',
    'sales forecasting (retail)',
    'employee relations',
    'recruitment and staffing',
    'hr compliance',
    'performance management',
    'training and development',
    'compensation and benefits administration',
    'hris (human resources information systems)',
    'employee engagement',
    'agricultural labor laws',
    'farmworker recruitment',
    'workforce management',
    'agricultural safety practices',
    'crop harvesting coordination',
    'collective bargaining',
    'conflict resolution',
    'labor law compliance',
    'negotiation skills',
    'grievance handling',
    'supply chain management',
    'inventory control',
    'logistics planning',
    'transportation management',
    'procurement',
    'vendor management',
    'process optimization',
    'systems analysis',
    'warehouse layout planning',
    'lean manufacturing',
    'six sigma',
    'data analysis',
    'report generation',
    'performance metrics tracking',
    'freight analysis',
    'logistics software proficiency',
    'project planning',
    'risk management',
    'budgeting',
    'stakeholder communication',
    'agile methodologies',
    'gantt chart creation',
    'management analysts:',
    'process improvement',
    'data analysis',
    'strategic planning',
    'business performance metrics',
    'market research',
    'meeting',
    'convention',
    'and event planners:',
    'event coordination',
    'budget management',
    'vendor negotiation',
    'contract management',
    'creative problem solving',
    'fundraisers:',
    'donor relations',
    'grant writing',
    'fundraising event planning',
    'campaign management',
    'relationship building',
    'compensation',
    'benefit',
    'and job analysis specialists:',
    'compensation analysis',
    'benefits administration',
    'job evaluation',
    'market salary surveys',
    'hr compliance',
    'training and development specialists:',
    'training program design',
    'learning management systems (lms)',
    'employee development',
    'training evaluation',
    'instructional design',
    'market research analysts and marketing specialists:',
    'data analysis',
    'market segmentation',
    'consumer behavior analysis',
    'competitor analysis',
    'survey design',
    'search marketing strategists:',
    'seo (search engine optimization)',
    'sem (search engine marketing)',
    'keyword research',
    'google analytics',
    'content strategy',
    'business operations specialists',
    'all other:',
    'process optimization',
    'data analysis',
    'change management',
    'quality assurance',
    'risk assessment',
    'business continuity planners:',
    'risk assessment',
    'crisis management',
    'disaster recovery planning',
    'business impact analysis',
    'emergency preparedness',
    'sustainability specialists:',
    'environmental impact assessment',
    'sustainable practices',
    'renewable energy strategies',
    'carbon footprint analysis',
    'eco-friendly initiatives',
    'online merchants:',
    'e-commerce platforms',
    'online marketing',
    'customer relationship management (crm)',
    'inventory management',
    'payment gateway integration',
    'security management specialists:',
    'security risk assessment',
    'access control',
    'emergency response planning',
    'security systems management',
    'threat analysis',
    'accountants and auditors:',
    'financial accounting',
    'auditing standards',
    'tax preparation',
    'budget analysis',
    'forensic accounting',
    'appraisers of personal and business property:',
    'valuation methods',
    'appraisal standards',
    'market analysis',
    'asset valuation',
    'reporting',
    'appraisers and assessors of real estate:',
    'real estate valuation',
    'property assessment',
    'market trends analysis',
    'regulatory compliance',
    'property inspection',
    'budget analysts:',
    'budget planning',
    'financial forecasting',
    'variance analysis',
    'cost estimation',
    'fiscal reporting',
    'credit analysts:',
    'credit risk assessment',
    'financial statement analysis',
    'credit scoring models',
    'loan evaluation',
    'regulatory compliance',
    'financial and investment analysts:',
    'investment analysis',
    'financial modeling',
    'portfolio management',
    'market trends analysis',
    'risk management',
    'personal financial advisors:',
    'financial planning',
    'investment planning',
    'retirement planning',
    'estate planning',
    'wealth management',
    'insurance underwriters:',
    'risk assessment',
    'underwriting guidelines',
    'insurance regulations',
    'policy analysis',
    'claims investigation',
    'financial risk specialists:',
    'risk management',
    'derivatives trading',
    'hedging strategies',
    'financial modeling',
    'compliance',
    'financial examiners:',
    'regulatory compliance',
    'financial auditing',
    'enforcement actions',
    'fraud detection',
    'reporting',
    'credit counselors:',
    'financial counseling',
    'debt management',
    'credit analysis',
    'budgeting assistance',
    'financial education',
    'loan officers:',
    'loan origination',
    'credit analysis',
    'risk assessment',
    'customer relationship management',
    'regulatory compliance',
    'tax examiners and collectors',
    'and revenue agents:',
    'tax compliance',
    'tax auditing',
    'tax code knowledge',
    'financial investigation',
    'reporting',
    'tax preparers:',
    'tax preparation',
    'irs regulations',
    'tax planning',
    'e-filing systems',
    'client communication',
    'financial specialists',
    'all other:',
    'financial consulting',
    'investment advisory',
    'due diligence',
    'financial project management',
    'regulatory compliance',
    'financial quantitative analysts:',
    'quantitative analysis',
    'mathematical modeling',
    'algorithm development',
    'statistical analysis',
    'programming (e.g.',
    'python',
    'r)',
    'fraud examiners',
    'investigators and analysts:',
    'fraud detection',
    'investigation techniques',
    'forensic accounting',
    'interview skills',
    'report writing',
    'computer systems analysts:',
    'systems analysis',
    'it project management',
    'business process modeling',
    'requirement gathering',
    'software integration',
    'health informatics specialists:',
    'electronic health records (ehr)',
    'health information exchange',
    'healthcare it systems',
    'data security in healthcare',
    'health informatics standards',
    'information security analysts:',
    'cybersecurity',
    'security risk assessment',
    'incident response',
    'security policy development',
    'penetration testing',
    'computer and information research scientists:',
    'algorithm development',
    'research methodologies',
    'computational theory',
    'data mining',
    'artificial intelligence',
    'computer network support specialists:',
    'network troubleshooting',
    'technical support',
    'network security',
    'hardware installation',
    'network monitoring',
    'computer user support specialists:',
    'help desk support',
    'customer service',
    'troubleshooting',
    'software installation',
    'user training',
    'computer network architects:',
    'network design',
    'network security',
    'cloud computing architecture',
    'protocols and standards',
    'ip addressing',
    'telecommunications engineering specialists:',
    'telecommunications systems']) # Replace with your actual file path
    # Initialize a list to store matching skills
    matching_skills = []
    nlp = spacy.load('en_core_web_lg')
        # Check similarity for each skill in the resume
    for skill_resume in resume_skills:
        if check_similarity(skill_resume, all_skills):
            matching_skills.append(skill_resume)

    # Display the matching skills
    #print("Matching Skills:", len(matching_skills), matching_skills
    final_skills = set(matching_skills)
    data = database.Database_common_operations.run_query_and_return_all_data("select Req from Job where JobId = 'J30';")
    skill_list = []
    fin_data = data[0][0].split(',')
    fin_data1 = fin_data[1:]
    for i in fin_data1:
        x = database.Database_common_operations.run_query_and_return_all_data(f"select Skill from Skills where SkillID = '{i}';")
        skill_list.append(x[0][0])

    print('\n')
    print("USER skills : ",final_skills)
    print("HR skills : ",skill_list)
    return compute_percentage_match(final_skills, skill_list,nlp)


nlp = spacy.load('en_core_web_lg')
# Function to compute percentage match between skills in resume and job description using word embeddings
def compute_percentage_match(resume_skills, job_description_skills, nlp):
    # Initialize counters
    matched_count = 0
    total_skills_in_resume = len(job_description_skills)

    # Check similarity for each skill in resume with job description skills
    for skill_resume in resume_skills:
        for skill_job_desc in job_description_skills:
            similarity = nlp(skill_resume).similarity(nlp(skill_job_desc))
            # If similarity score is above threshold, consider it as a match
            if similarity >= 0.55:  # Adjust threshold as needed
                matched_count += 1
                break  # Move to the next skill in resume

    # Compute percentage match
    l_resume = [item.lower() for item in resume_skills]
    l_job = [item.lower() for item in job_description_skills]
    len_of_inter = len(list(set(l_resume) & set(l_job)))

    percentage_match = (len_of_inter/total_skills_in_resume)*100

    return round(percentage_match), resume_skills

# from fuzzywuzzy import fuzz

# # Function to compute percentage match between skills in resume and job description
# def compute_percentage_match(resume_skills, job_description_skills):
#     # Initialize counters
#     matched_count = 0
#     total_skills_in_resume = len( job_description_skills)

#     # Check similarity for each skill in resume with job description skills
#     for skill_resume in resume_skills:
#         for skill_job_desc in job_description_skills:
#             similarity = fuzz.token_set_ratio(skill_resume, skill_job_desc)
#             # If similarity score is above threshold, consider it as a match
#             if similarity >= 100:  # Adjust threshold as needed
#                 matched_count += 1
#                 break  # Move to the next skill in resume
#     print(matched_count)
#     # Compute percentage match
#     percentage_match = (matched_count / total_skills_in_resume) * 100
#     # Print the percentage match
#     print("Percentage match between resume skills and job description skills:", percentage_match)
    
#     return percentage_match

